# -*- coding: utf-8 -*-
from odoo import fields, models


class AccountAnalyticLine(models.Model):
    _inherit = "account.analytic.line"

    edlab_is_royalty_payment = fields.Boolean(
        string="Royalty Payment Line",
        index=True,
        help="Set on the analytic line generated by a royalty payment vendor "
        "bill. Such lines record the actual cash cost on the analytic account "
        "but are excluded from the 'Open Royalties' owed balance, which is "
        "settled through the beneficiary's last payment date instead.",
    )
